"""create_submissions

Revision ID: b6281ee61401
Revises: 98b8db8cb9ac
Create Date: 2026-06-17 00:36:35.932023

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b6281ee61401'
down_revision: Union[str, Sequence[str], None] = '98b8db8cb9ac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'submissions',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('project_id', sa.UUID(), nullable=False),
        sa.Column('version', sa.Integer(), nullable=False),
        sa.Column('file_path', sa.String(length=1000), nullable=False),
        sa.Column('filename', sa.String(length=255), nullable=False),
        sa.Column('original_filename', sa.String(length=500), nullable=True),
        sa.Column('uploader_id', sa.UUID(), nullable=True),
        sa.Column('task_title', sa.String(length=255), nullable=True),
        sa.Column('feedback', sa.Text(), nullable=True),
        sa.Column('status', sa.String(length=20), nullable=False, server_default='pending'),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['uploader_id'], ['users.id'], ondelete='SET NULL'),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('idx_submissions_project_id'), 'submissions', ['project_id'], unique=False)
    op.create_index(op.f('idx_submissions_uploader_id'), 'submissions', ['uploader_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('idx_submissions_uploader_id'), table_name='submissions')
    op.drop_index(op.f('idx_submissions_project_id'), table_name='submissions')
    op.drop_table('submissions')
    # ### end Alembic commands ###
